
// Description: Java7 DbIO interface for Tenant.

/*
 *	CFBam
 *
 *	Copyright (c) 2014-2015 Mark Sobkow
 *	
 *	This program is available as free software under the GNU GPL v3, under
 *	the Eclipse Public License 1.0, or under a commercial license from Mark
 *	Sobkow.  For commercial licensing details, please contact msobkow@sasktel.net.
 *	
 *	You should have received copies of the complete license text for
 *	GPLv3.txt and EPLv1_0.txt, containing the text
 *	of the GNU General Public License v 3.0 and the Eclipse Public License v 1.0.
 *	
 *	Under the terms of the GPL:
 *	
 *		This program is free software: you can redistribute it and/or modify
 *		it under the terms of the GNU General Public License as published by
 *		the Free Software Foundation, either version 3 of the License, or
 *		(at your option) any later version.
 *	  
 *		This program is distributed in the hope that it will be useful,
 *		but WITHOUT ANY WARRANTY; without even the implied warranty of
 *		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *		GNU General Public License for more details.
 *	  
 *		You should have received a copy of the GNU General Public License
 *		along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *	
 *	This software incorporates code originally Copyright (c) Mark Sobkow 2014-2015
 *	and licensed under the BSD 3-Clause license as written by xfree86.org:
 *	
 *	Redistribution and use in source and binary forms, with or without
 *	modification, are permitted provided that the following conditions are
 *	met:
 *	
 *	    (1) Redistributions of source code must retain the above copyright
 *	    notice, this list of conditions and the following disclaimer. 
 *	
 *	    (2) Redistributions in binary form must reproduce the above copyright
 *	    notice, this list of conditions and the following disclaimer in
 *	    the documentation and/or other materials provided with the
 *	    distribution.  
 *	    
 *	    (3)The name of the author may not be used to
 *	    endorse or promote products derived from this software without
 *	    specific prior written permission.
 *	
 *	THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 *	IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *	DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
 *	INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *	(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 *	SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 *	HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 *	STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 *	IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *	POSSIBILITY OF SUCH DAMAGE.
 *	
 * ***********************************************************************
 *
 *	Code manufactured by MSS Code Factory
 */


package net.sourceforge.msscodefactory.cfbam.v2_3.CFBam;

import java.lang.reflect.*;
import java.net.*;
import java.rmi.*;
import java.sql.*;
import java.text.*;
import java.util.*;
import net.sourceforge.msscodefactory.cflib.v2_3.CFLib.*;

/*
 *	CFBamTenantTable DbIO interface for Tenant
 */
public interface ICFBamTenantTable
{
	/**
	 *	Get the next TSecGroupIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Tenant instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	int nextTSecGroupIdGen( CFBamAuthorization Authorization,
		CFBamTenantPKey PKey );

	/**
	 *	Get the next TSecGroupIdGen id generator value.
	 *
	 *	@param	argId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	int nextTSecGroupIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next TSecGroupMemberIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Tenant instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextTSecGroupMemberIdGen( CFBamAuthorization Authorization,
		CFBamTenantPKey PKey );

	/**
	 *	Get the next TSecGroupMemberIdGen id generator value.
	 *
	 *	@param	argId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextTSecGroupMemberIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next TSecGroupIncludeIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Tenant instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextTSecGroupIncludeIdGen( CFBamAuthorization Authorization,
		CFBamTenantPKey PKey );

	/**
	 *	Get the next TSecGroupIncludeIdGen id generator value.
	 *
	 *	@param	argId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextTSecGroupIncludeIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next TldIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Tenant instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextTldIdGen( CFBamAuthorization Authorization,
		CFBamTenantPKey PKey );

	/**
	 *	Get the next TldIdGen id generator value.
	 *
	 *	@param	argId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextTldIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next DomainIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Tenant instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextDomainIdGen( CFBamAuthorization Authorization,
		CFBamTenantPKey PKey );

	/**
	 *	Get the next DomainIdGen id generator value.
	 *
	 *	@param	argId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextDomainIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next ScopeIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Tenant instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextScopeIdGen( CFBamAuthorization Authorization,
		CFBamTenantPKey PKey );

	/**
	 *	Get the next ScopeIdGen id generator value.
	 *
	 *	@param	argId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextScopeIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next IndexColIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Tenant instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextIndexColIdGen( CFBamAuthorization Authorization,
		CFBamTenantPKey PKey );

	/**
	 *	Get the next IndexColIdGen id generator value.
	 *
	 *	@param	argId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextIndexColIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next LicenseIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Tenant instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextLicenseIdGen( CFBamAuthorization Authorization,
		CFBamTenantPKey PKey );

	/**
	 *	Get the next LicenseIdGen id generator value.
	 *
	 *	@param	argId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextLicenseIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next RelationColIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Tenant instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextRelationColIdGen( CFBamAuthorization Authorization,
		CFBamTenantPKey PKey );

	/**
	 *	Get the next RelationColIdGen id generator value.
	 *
	 *	@param	argId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextRelationColIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next ValueIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Tenant instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextValueIdGen( CFBamAuthorization Authorization,
		CFBamTenantPKey PKey );

	/**
	 *	Get the next ValueIdGen id generator value.
	 *
	 *	@param	argId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextValueIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next EnumTagIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Tenant instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextEnumTagIdGen( CFBamAuthorization Authorization,
		CFBamTenantPKey PKey );

	/**
	 *	Get the next EnumTagIdGen id generator value.
	 *
	 *	@param	argId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextEnumTagIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next ChainIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Tenant instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextChainIdGen( CFBamAuthorization Authorization,
		CFBamTenantPKey PKey );

	/**
	 *	Get the next ChainIdGen id generator value.
	 *
	 *	@param	argId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextChainIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next ParamIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Tenant instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextParamIdGen( CFBamAuthorization Authorization,
		CFBamTenantPKey PKey );

	/**
	 *	Get the next ParamIdGen id generator value.
	 *
	 *	@param	argId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextParamIdGen( CFBamAuthorization Authorization,
		long argId );


	/**
	 *	Create the instance in the database, and update the specified buffer
	 *	with the assigned primary key.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	Buff	The buffer to be created.
	 */
	void createTenant( CFBamAuthorization Authorization,
		CFBamTenantBuff Buff );


	/**
	 *	Update the instance in the database, and update the specified buffer
	 *	with any calculated changes imposed by the associated stored procedure.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	Buff	The buffer to be updated.
	 */
	void updateTenant( CFBamAuthorization Authorization,
		CFBamTenantBuff Buff );


	/**
	 *	Delete the instance from the database.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	Buff	The buffer to be deleted.
	 */
	void deleteTenant( CFBamAuthorization Authorization,
		CFBamTenantBuff Buff );
	/**
	 *	Delete the Tenant instance identified by the primary key attributes.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argId	The Tenant key attribute of the instance generating the id.
	 */
	void deleteTenantByIdIdx( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Delete the Tenant instance identified by the primary key.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argKey	The primary key identifying the instance to be deleted.
	 */
	void deleteTenantByIdIdx( CFBamAuthorization Authorization,
		CFBamTenantPKey argKey );
	/**
	 *	Delete the Tenant instances identified by the key ClusterIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argClusterId	The Tenant key attribute of the instance generating the id.
	 */
	void deleteTenantByClusterIdx( CFBamAuthorization Authorization,
		long argClusterId );

	/**
	 *	Delete the Tenant instances identified by the key ClusterIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argKey	The key identifying the instances to be deleted.
	 */
	void deleteTenantByClusterIdx( CFBamAuthorization Authorization,
		CFBamTenantByClusterIdxKey argKey );
	/**
	 *	Delete the Tenant instances identified by the key UNameIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argClusterId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@param	argTenantName	The Tenant key attribute of the instance generating the id.
	 */
	void deleteTenantByUNameIdx( CFBamAuthorization Authorization,
		long argClusterId,
		String argTenantName );

	/**
	 *	Delete the Tenant instances identified by the key UNameIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argKey	The key identifying the instances to be deleted.
	 */
	void deleteTenantByUNameIdx( CFBamAuthorization Authorization,
		CFBamTenantByUNameIdxKey argKey );

	/**
	 *	Open a cursor over all the instances of Tenant.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return CFBamCursor over Tenant for the specfied key
	 *		of the index.
	 */
	CFBamCursor openTenantCursorAll( CFBamAuthorization Authorization );
	/**
	 *	Open a cursor over the specified index key value.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return CFBamCursor over Tenant for the specfied key
	 *		of the index.
	 */
	CFBamCursor openTenantCursorByClusterIdx( CFBamAuthorization Authorization,
		long ClusterId );
	/**
	 *	Close the specified cursor.
	 *
	 *	@param	Cursor	The cursor to close.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 */
	void closeTenantCursor( CFBamCursor Cursor );
	/**
	 *	Get the next instance of a Tenant for the specified cursor.
	 *
	 *	@param	Cursor	The cursor to get the next instance of.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamTenantBuff nextTenantCursor( CFBamCursor Cursor );
	/**
	 *	Get the previous instance of a Tenant for the specified cursor.
	 *
	 *	@param	Cursor	The cursor to get the previous instance of.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamTenantBuff prevTenantCursor( CFBamCursor Cursor );
	/**
	 *	Get the first instance of a Tenant for the specified cursor.
	 *
	 *	@param	Cursor	The cursor to get the first instance of.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamTenantBuff firstTenantCursor( CFBamCursor Cursor );
	/**
	 *	Get the last instance of a Tenant for the specified cursor.
	 *
	 *	@param	Cursor	The cursor to get the last instance of.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamTenantBuff lastTenantCursor( CFBamCursor Cursor );
	/**
	 *	Get the nth instance of a Tenant for the specified cursor.
	 *
	 *	@param	Cursor	The cursor to get the first instance of.
	 *
	 *	@param	Idx	The zero-based cursor index.  0 is the first instance.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamTenantBuff nthTenantCursor( CFBamCursor Cursor, int Idx );

	/**
	 *	Read the derived Tenant buffer instance by primary key.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	PKey	The primary key of the Tenant instance to be read.
	 *
	 *	@return The buffer instance for the specified primary key, or null if there is
	 *		no such existing key value.
	 */
	CFBamTenantBuff readDerived( CFBamAuthorization Authorization,
		CFBamTenantPKey PKey );

	/**
	 *	Lock the derived Tenant buffer instance by primary key.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	PKey	The primary key of the Tenant instance to be locked.
	 *
	 *	@return The buffer instance for the specified primary key, or null if there is
	 *		no such existing key value.
	 */
	CFBamTenantBuff lockDerived( CFBamAuthorization Authorization,
		CFBamTenantPKey PKey );

	/**
	 *	Read all Tenant instances.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@return An array of derived buffer instances, potentially with 0 elements in the set.
	 */
	CFBamTenantBuff[] readAllDerived( CFBamAuthorization Authorization );

	/**
	 *	Read the derived Tenant buffer instance identified by the unique key IdIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@return The buffer instance for the specified key, or null if there is
	 *		no such existing key value.
	 */
	CFBamTenantBuff readDerivedByIdIdx( CFBamAuthorization Authorization,
		long Id );

	/**
	 *	Read an array of the derived Tenant buffer instances identified by the duplicate key ClusterIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argClusterId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@return An array of derived buffer instances for the specified key, potentially with 0 elements in the set.
	 */
	CFBamTenantBuff[] readDerivedByClusterIdx( CFBamAuthorization Authorization,
		long ClusterId );

	/**
	 *	Read the derived Tenant buffer instance identified by the unique key UNameIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argClusterId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@param	argTenantName	The Tenant key attribute of the instance generating the id.
	 *
	 *	@return The buffer instance for the specified key, or null if there is
	 *		no such existing key value.
	 */
	CFBamTenantBuff readDerivedByUNameIdx( CFBamAuthorization Authorization,
		long ClusterId,
		String TenantName );

	/**
	 *	Read the specific Tenant buffer instance identified by the primary key.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	PKey	The primary key of the Tenant instance to be locked.
	 *
	 *	@return The buffer instance for the specified primary key, or null if there is
	 *		no such existing key value.
	 *
	 *	@throws	CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamTenantBuff readBuff( CFBamAuthorization Authorization,
		CFBamTenantPKey PKey );

	/**
	 *	Lock the specific Tenant buffer instance identified by the primary key.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	PKey	The primary key of the Tenant instance to be locked.
	 *
	 *	@return The buffer instance for the specified primary key, or null if there is
	 *		no such existing key value.
	 *
	 *	@throws	CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamTenantBuff lockBuff( CFBamAuthorization Authorization,
		CFBamTenantPKey PKey );

	/**
	 *	Read all the specific Tenant buffer instances.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@return All the specific Tenant instances in the database accessible for the Authorization.
	 */
	CFBamTenantBuff[] readAllBuff( CFBamAuthorization Authorization );

	/**
	 *	Read the specific Tenant buffer instance identified by the unique key IdIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@return The buffer instance for the specified key, or null if there is
	 *		no such existing key value.
	 *
	 *	@throws	CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamTenantBuff readBuffByIdIdx( CFBamAuthorization Authorization,
		long Id );

	/**
	 *	Read an array of the specific Tenant buffer instances identified by the duplicate key ClusterIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argClusterId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@return An array of derived buffer instances for the specified key, potentially with 0 elements in the set.
	 *
	 *	@throws	CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamTenantBuff[] readBuffByClusterIdx( CFBamAuthorization Authorization,
		long ClusterId );

	/**
	 *	Read the specific Tenant buffer instance identified by the unique key UNameIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argClusterId	The Tenant key attribute of the instance generating the id.
	 *
	 *	@param	argTenantName	The Tenant key attribute of the instance generating the id.
	 *
	 *	@return The buffer instance for the specified key, or null if there is
	 *		no such existing key value.
	 *
	 *	@throws	CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamTenantBuff readBuffByUNameIdx( CFBamAuthorization Authorization,
		long ClusterId,
		String TenantName );

	/**
	 *	Release any prepared statements allocated by this instance.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 */
	void releasePreparedStatements();
}
