
// Description: Java7 DbIO interface for Cluster.

/*
 *	CFBam
 *
 *	Copyright (c) 2014-2015 Mark Sobkow
 *	
 *	This program is available as free software under the GNU GPL v3, under
 *	the Eclipse Public License 1.0, or under a commercial license from Mark
 *	Sobkow.  For commercial licensing details, please contact msobkow@sasktel.net.
 *	
 *	You should have received copies of the complete license text for
 *	GPLv3.txt and EPLv1_0.txt, containing the text
 *	of the GNU General Public License v 3.0 and the Eclipse Public License v 1.0.
 *	
 *	Under the terms of the GPL:
 *	
 *		This program is free software: you can redistribute it and/or modify
 *		it under the terms of the GNU General Public License as published by
 *		the Free Software Foundation, either version 3 of the License, or
 *		(at your option) any later version.
 *	  
 *		This program is distributed in the hope that it will be useful,
 *		but WITHOUT ANY WARRANTY; without even the implied warranty of
 *		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *		GNU General Public License for more details.
 *	  
 *		You should have received a copy of the GNU General Public License
 *		along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *	
 *	This software incorporates code originally Copyright (c) Mark Sobkow 2014-2015
 *	and licensed under the BSD 3-Clause license as written by xfree86.org:
 *	
 *	Redistribution and use in source and binary forms, with or without
 *	modification, are permitted provided that the following conditions are
 *	met:
 *	
 *	    (1) Redistributions of source code must retain the above copyright
 *	    notice, this list of conditions and the following disclaimer. 
 *	
 *	    (2) Redistributions in binary form must reproduce the above copyright
 *	    notice, this list of conditions and the following disclaimer in
 *	    the documentation and/or other materials provided with the
 *	    distribution.  
 *	    
 *	    (3)The name of the author may not be used to
 *	    endorse or promote products derived from this software without
 *	    specific prior written permission.
 *	
 *	THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 *	IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *	DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
 *	INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *	(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 *	SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 *	HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 *	STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 *	IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *	POSSIBILITY OF SUCH DAMAGE.
 *	
 * ***********************************************************************
 *
 *	Code manufactured by MSS Code Factory
 */


package net.sourceforge.msscodefactory.cfbam.v2_3.CFBam;

import java.lang.reflect.*;
import java.net.*;
import java.rmi.*;
import java.sql.*;
import java.text.*;
import java.util.*;
import net.sourceforge.msscodefactory.cflib.v2_3.CFLib.*;

/*
 *	CFBamClusterTable DbIO interface for Cluster
 */
public interface ICFBamClusterTable
{
	/**
	 *	Get the next SecAppIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Cluster instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	int nextSecAppIdGen( CFBamAuthorization Authorization,
		CFBamClusterPKey PKey );

	/**
	 *	Get the next SecAppIdGen id generator value.
	 *
	 *	@param	argId	The Cluster key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	int nextSecAppIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next SecFormIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Cluster instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	int nextSecFormIdGen( CFBamAuthorization Authorization,
		CFBamClusterPKey PKey );

	/**
	 *	Get the next SecFormIdGen id generator value.
	 *
	 *	@param	argId	The Cluster key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	int nextSecFormIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next SecGroupIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Cluster instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	int nextSecGroupIdGen( CFBamAuthorization Authorization,
		CFBamClusterPKey PKey );

	/**
	 *	Get the next SecGroupIdGen id generator value.
	 *
	 *	@param	argId	The Cluster key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	int nextSecGroupIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next SecGroupMemberIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Cluster instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextSecGroupMemberIdGen( CFBamAuthorization Authorization,
		CFBamClusterPKey PKey );

	/**
	 *	Get the next SecGroupMemberIdGen id generator value.
	 *
	 *	@param	argId	The Cluster key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextSecGroupMemberIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next SecGroupIncludeIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Cluster instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextSecGroupIncludeIdGen( CFBamAuthorization Authorization,
		CFBamClusterPKey PKey );

	/**
	 *	Get the next SecGroupIncludeIdGen id generator value.
	 *
	 *	@param	argId	The Cluster key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextSecGroupIncludeIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next SecGroupFormIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Cluster instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextSecGroupFormIdGen( CFBamAuthorization Authorization,
		CFBamClusterPKey PKey );

	/**
	 *	Get the next SecGroupFormIdGen id generator value.
	 *
	 *	@param	argId	The Cluster key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextSecGroupFormIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next ServiceIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Cluster instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextServiceIdGen( CFBamAuthorization Authorization,
		CFBamClusterPKey PKey );

	/**
	 *	Get the next ServiceIdGen id generator value.
	 *
	 *	@param	argId	The Cluster key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextServiceIdGen( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Get the next HostNodeIdGen id generator value.
	 *
	 *	@param	PKey	The primary key of the Cluster instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextHostNodeIdGen( CFBamAuthorization Authorization,
		CFBamClusterPKey PKey );

	/**
	 *	Get the next HostNodeIdGen id generator value.
	 *
	 *	@param	argId	The Cluster key attribute of the instance generating the id.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return The next id value as generated by the cluster database.
	 */
	long nextHostNodeIdGen( CFBamAuthorization Authorization,
		long argId );


	/**
	 *	Create the instance in the database, and update the specified buffer
	 *	with the assigned primary key.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	Buff	The buffer to be created.
	 */
	void createCluster( CFBamAuthorization Authorization,
		CFBamClusterBuff Buff );


	/**
	 *	Update the instance in the database, and update the specified buffer
	 *	with any calculated changes imposed by the associated stored procedure.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	Buff	The buffer to be updated.
	 */
	void updateCluster( CFBamAuthorization Authorization,
		CFBamClusterBuff Buff );


	/**
	 *	Delete the instance from the database.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	Buff	The buffer to be deleted.
	 */
	void deleteCluster( CFBamAuthorization Authorization,
		CFBamClusterBuff Buff );
	/**
	 *	Delete the Cluster instance identified by the primary key attributes.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argId	The Cluster key attribute of the instance generating the id.
	 */
	void deleteClusterByIdIdx( CFBamAuthorization Authorization,
		long argId );

	/**
	 *	Delete the Cluster instance identified by the primary key.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argKey	The primary key identifying the instance to be deleted.
	 */
	void deleteClusterByIdIdx( CFBamAuthorization Authorization,
		CFBamClusterPKey argKey );
	/**
	 *	Delete the Cluster instances identified by the key UDomainNameIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argFullDomainName	The Cluster key attribute of the instance generating the id.
	 */
	void deleteClusterByUDomainNameIdx( CFBamAuthorization Authorization,
		String argFullDomainName );

	/**
	 *	Delete the Cluster instances identified by the key UDomainNameIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argKey	The key identifying the instances to be deleted.
	 */
	void deleteClusterByUDomainNameIdx( CFBamAuthorization Authorization,
		CFBamClusterByUDomainNameIdxKey argKey );
	/**
	 *	Delete the Cluster instances identified by the key UDescrIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argDescription	The Cluster key attribute of the instance generating the id.
	 */
	void deleteClusterByUDescrIdx( CFBamAuthorization Authorization,
		String argDescription );

	/**
	 *	Delete the Cluster instances identified by the key UDescrIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argKey	The key identifying the instances to be deleted.
	 */
	void deleteClusterByUDescrIdx( CFBamAuthorization Authorization,
		CFBamClusterByUDescrIdxKey argKey );

	/**
	 *	Open a cursor over all the instances of Cluster.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 *
	 *	@return CFBamCursor over Cluster for the specfied key
	 *		of the index.
	 */
	CFBamCursor openClusterCursorAll( CFBamAuthorization Authorization );
	/**
	 *	Close the specified cursor.
	 *
	 *	@param	Cursor	The cursor to close.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 */
	void closeClusterCursor( CFBamCursor Cursor );
	/**
	 *	Get the next instance of a Cluster for the specified cursor.
	 *
	 *	@param	Cursor	The cursor to get the next instance of.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamClusterBuff nextClusterCursor( CFBamCursor Cursor );
	/**
	 *	Get the previous instance of a Cluster for the specified cursor.
	 *
	 *	@param	Cursor	The cursor to get the previous instance of.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamClusterBuff prevClusterCursor( CFBamCursor Cursor );
	/**
	 *	Get the first instance of a Cluster for the specified cursor.
	 *
	 *	@param	Cursor	The cursor to get the first instance of.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamClusterBuff firstClusterCursor( CFBamCursor Cursor );
	/**
	 *	Get the last instance of a Cluster for the specified cursor.
	 *
	 *	@param	Cursor	The cursor to get the last instance of.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamClusterBuff lastClusterCursor( CFBamCursor Cursor );
	/**
	 *	Get the nth instance of a Cluster for the specified cursor.
	 *
	 *	@param	Cursor	The cursor to get the first instance of.
	 *
	 *	@param	Idx	The zero-based cursor index.  0 is the first instance.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamClusterBuff nthClusterCursor( CFBamCursor Cursor, int Idx );

	/**
	 *	Read the derived Cluster buffer instance by primary key.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	PKey	The primary key of the Cluster instance to be read.
	 *
	 *	@return The buffer instance for the specified primary key, or null if there is
	 *		no such existing key value.
	 */
	CFBamClusterBuff readDerived( CFBamAuthorization Authorization,
		CFBamClusterPKey PKey );

	/**
	 *	Lock the derived Cluster buffer instance by primary key.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	PKey	The primary key of the Cluster instance to be locked.
	 *
	 *	@return The buffer instance for the specified primary key, or null if there is
	 *		no such existing key value.
	 */
	CFBamClusterBuff lockDerived( CFBamAuthorization Authorization,
		CFBamClusterPKey PKey );

	/**
	 *	Read all Cluster instances.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@return An array of derived buffer instances, potentially with 0 elements in the set.
	 */
	CFBamClusterBuff[] readAllDerived( CFBamAuthorization Authorization );

	/**
	 *	Read the derived Cluster buffer instance identified by the unique key IdIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argId	The Cluster key attribute of the instance generating the id.
	 *
	 *	@return The buffer instance for the specified key, or null if there is
	 *		no such existing key value.
	 */
	CFBamClusterBuff readDerivedByIdIdx( CFBamAuthorization Authorization,
		long Id );

	/**
	 *	Read the derived Cluster buffer instance identified by the unique key UDomainNameIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argFullDomainName	The Cluster key attribute of the instance generating the id.
	 *
	 *	@return The buffer instance for the specified key, or null if there is
	 *		no such existing key value.
	 */
	CFBamClusterBuff readDerivedByUDomainNameIdx( CFBamAuthorization Authorization,
		String FullDomainName );

	/**
	 *	Read the derived Cluster buffer instance identified by the unique key UDescrIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argDescription	The Cluster key attribute of the instance generating the id.
	 *
	 *	@return The buffer instance for the specified key, or null if there is
	 *		no such existing key value.
	 */
	CFBamClusterBuff readDerivedByUDescrIdx( CFBamAuthorization Authorization,
		String Description );

	/**
	 *	Read the specific Cluster buffer instance identified by the primary key.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	PKey	The primary key of the Cluster instance to be locked.
	 *
	 *	@return The buffer instance for the specified primary key, or null if there is
	 *		no such existing key value.
	 *
	 *	@throws	CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamClusterBuff readBuff( CFBamAuthorization Authorization,
		CFBamClusterPKey PKey );

	/**
	 *	Lock the specific Cluster buffer instance identified by the primary key.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	PKey	The primary key of the Cluster instance to be locked.
	 *
	 *	@return The buffer instance for the specified primary key, or null if there is
	 *		no such existing key value.
	 *
	 *	@throws	CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamClusterBuff lockBuff( CFBamAuthorization Authorization,
		CFBamClusterPKey PKey );

	/**
	 *	Read all the specific Cluster buffer instances.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@return All the specific Cluster instances in the database accessible for the Authorization.
	 */
	CFBamClusterBuff[] readAllBuff( CFBamAuthorization Authorization );

	/**
	 *	Read the specific Cluster buffer instance identified by the unique key IdIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argId	The Cluster key attribute of the instance generating the id.
	 *
	 *	@return The buffer instance for the specified key, or null if there is
	 *		no such existing key value.
	 *
	 *	@throws	CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamClusterBuff readBuffByIdIdx( CFBamAuthorization Authorization,
		long Id );

	/**
	 *	Read the specific Cluster buffer instance identified by the unique key UDomainNameIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argFullDomainName	The Cluster key attribute of the instance generating the id.
	 *
	 *	@return The buffer instance for the specified key, or null if there is
	 *		no such existing key value.
	 *
	 *	@throws	CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamClusterBuff readBuffByUDomainNameIdx( CFBamAuthorization Authorization,
		String FullDomainName );

	/**
	 *	Read the specific Cluster buffer instance identified by the unique key UDescrIdx.
	 *
	 *	@param	Authorization	The session authorization information.
	 *
	 *	@param	argDescription	The Cluster key attribute of the instance generating the id.
	 *
	 *	@return The buffer instance for the specified key, or null if there is
	 *		no such existing key value.
	 *
	 *	@throws	CFLibNotSupportedException thrown by client-side implementations.
	 */
	CFBamClusterBuff readBuffByUDescrIdx( CFBamAuthorization Authorization,
		String Description );

	/**
	 *	Release any prepared statements allocated by this instance.
	 *
	 *	@throws CFLibNotSupportedException thrown by client-side implementations.
	 */
	void releasePreparedStatements();
}
